In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv("professions_enriched.csv");

In [15]:
df.sample(12)

profession  count statut public_prive  \
204  Dessinatrice industrielle Michelin      1  actif        prive   
162             Enseignante et écrivain      1  actif       public   
279               Chirurgien plasticien      1  actif        prive   
262         Conseiller en communication      2  actif        prive   
212                  Auditeur financier      1  actif        prive   
138                           Urbaniste      2  actif        prive   
302      Médecin neurologue hospitalier      1  actif       public   
145             Agrégé de mathématiques      1  actif       public   
94   Conseiller des affaires étrangères      1  actif       public   
118                              Préfet      3  actif       public   
174                   Professeur agrégé      1  actif       public   
164                         Instituteur      2  actif       public   

                         fonction  
204                  Fabrication   
162         Education, formation   
279                Santé, social   
262  Prestations intellectuelles   
212                       Gestion  
138    Bâtiment, travaux publics   
302                Santé, social   
145         Education, formation   
94       Administration publique   
118      Administration publique   
174         Education, formation   
164         Education, formation

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df['profession'].values)
X_train_counts.shape

(328, 354)

In [30]:
count_vect.vocabulary_

{'1er': 0,
 '2007': 1,
 'acconage': 2,
 'action': 3,
 'activité': 4,
 'adjoint': 5,
 'administrateur': 6,
 'administratif': 7,
 'affaires': 8,
 'agence': 9,
 'agent': 10,
 'agricole': 11,
 'agriculteur': 12,
 'agricultrice': 13,
 'agriculture': 14,
 'agronome': 15,
 'agrégé': 16,
 'ancien': 17,
 'ancienne': 18,
 'anesthésiste': 19,
 'annecy': 20,
 'appel': 21,
 'architecte': 22,
 'artisan': 23,
 'artiste': 24,
 'assemblée': 25,
 'assistant': 26,
 'assistante': 27,
 'associatif': 28,
 'associé': 29,
 'associée': 30,
 'assurance': 31,
 'assurances': 32,
 'assureur': 33,
 'atlantiques': 34,
 'attaché': 35,
 'attachée': 36,
 'au': 37,
 'audit': 38,
 'auditeur': 39,
 'auprès': 40,
 'autre': 41,
 'aux': 42,
 'avocat': 43,
 'avocate': 44,
 'aéronautique': 45,
 'bancaire': 46,
 'banque': 47,
 'barreau': 48,
 'biens': 49,
 'biologiste': 50,
 'bordeaux': 51,
 'bretagne': 52,
 'bâtonnier': 53,
 'cabinet': 54,
 'cadre': 55,
 'cardiologue': 56,
 'catégorie': 57,
 'centre': 58,
 'certifié': 59,
 'ch

In [27]:
pd.DataFrame(X_train_counts.toarray()).sample(10)

0    1    2    3    4    5    6    7    8    9   ...   344  345  346  \
71     0    0    0    0    0    0    1    0    0    0 ...     0    0    0   
176    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
251    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
203    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
318    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
172    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
217    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
297    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
117    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
119    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   

     347  348  349  350  351  352  353  
71     0    0    0    0    0    0    0  
176    0    0    0    0    0    0    0  
251    0    0    0    0    0    0    0  
203    0    0    0    0    0    0    0  
318    0    0    0    0    0    0    0  
172    0    0    0    0    0    0    0  
217    0    0    0    0    0    0    0  
297    0    0    0    0    0    0    0  
117    0    0    0    0    0    0    0  
119    0    0    0    0    0    0    0  

[10 rows x 354 columns]

In [25]:
#count_vect.vocabulary_.items()

In [21]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(328, 354)

In [26]:
pd.DataFrame(X_train_tf.toarray())

0    1    2    3    4    5        6    7    8         9      ...     344  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.57735  0.0  0.0  0.000000    ...     0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
5    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
6    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
7    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
8    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
9    0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
10   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
11   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
12   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
13   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
14   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
15   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
16   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
17   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
18   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
19   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
20   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
21   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
22   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
23   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
24   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
25   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
26   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.5  0.0  0.000000    ...     0.0   
27   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
28   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
29   0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
..   ...  ...  ...  ...  ...  ...      ...  ...  ...       ...    ...     ...   
298  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
299  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
300  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
301  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
302  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
303  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
304  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
305  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
306  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
307  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
308  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
309  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
310  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
311  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
312  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
313  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
314  0.0  0.0  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.000000    ...     0.0   
315  0.0  0.0  0.0  0.0  0.0  0.0  0

In [9]:
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


In [10]:
targets = ['statut', 'public_prive', 'fonction'];
df_train = df[df['fonction'] != '??']
for tgt in targets:
    print(tgt);
    clf = Pipeline([('vect', CountVectorizer()),
                         ('tfidf', TfidfTransformer()),
                         ('clf', MultinomialNB()),
    ])
    clf = clf.fit(df_train['profession'].values, df_train[tgt].values)
    print(clf.score(df_train['profession'].values, df_train[tgt].values))
    predicted = clf.predict(df['profession'].values)
    df['predicted_' + tgt] = predicted
    print(metrics.confusion_matrix(df[tgt].values, df['predicted_' + tgt].values))

statut
0.919540229885
[[  0   0   1   0]
 [  0   0   3   0]
 [  0   0 289   0]
 [  0   0  31   4]]
public_prive
0.95785440613
[[  0   4   4]
 [  0 131  26]
 [  0   9 154]]
fonction
0.800766283525
[[ 0 31  0  0  0 18  0  0 10  0  8  0  0]
 [ 0 55  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  0  0  7  0  0  0  0  1  0  0]
 [ 0  3  0  0  0  2  0  0  1  0  0  0  0]
 [ 0  1  0  0  0  2  0  0  2  0  1  0  0]
 [ 0  0  0  0  0 54  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  2  0  0  3  0  0  0  0]
 [ 0  1  0  0  0  0  0  0 43  0  0  0  0]
 [ 0  6  0  0  0  1  0  0  4  5  0  0  0]
 [ 0  0  0  0  0  1  0  0  1  0 50  0  0]
 [ 0  1  0  0  0  4  0  0  1  0  1  0  0]
 [ 0  0  0  0  0  2  0  0  1  0  0  0  0]]


In [11]:
df_test = df[df['fonction'] == '??']

In [12]:
df_test

profession  count           statut  \
0                             Administrateur de biens      1            actif   
1                         Agent de contrôle retraitée      1         retraite   
2                                           Agent EDF      1            actif   
3                                        Agent public      1            actif   
4                     Agent technique et technicienne      1            actif   
5       Ancien directeur d'une société de recrutement      1         retraite   
6                                Attaché de direction      2            actif   
7                                    Autre profession      4            actif   
8                                               Cadre      7            actif   
9        Cadre A de la fonction publique territoriale      2            actif   
10                                 Cadre de direction      1            actif   
11                      Cadre de la fonction publique      1            actif   
12         Cadre de la fonction publique territoriale      1            actif   
13                                   Cadre de société      1            actif   
14                   Cadre dirigeant du secteur privé      1            actif   
15                             Cadre du secteur privé     13            actif   
16                    Cadre du secteur privé retraité      1         retraite   
17                            Cadre du secteur public      3            actif   
18                                         Cadre ERDF      1            actif   
19                                    Cadre supérieur      1            actif   
20  Cadre supérieur de la fonction publique, direc...      1            actif   
21                   Cadre supérieur du secteur privé     21            actif   
22                                   Chargée d'études      1            actif   
23                                 Chargée de mission      1            actif   
24                         Chef d'entreprise retraité      1         retraite   
25  Contractuel dans la Fonction publique territor...      1            actif   
26               Directeur administratif et financier      1            actif   
27                       Directeur associé de société      1            actif   
28                  Directeur de programme immobilier      1            actif   
29                               Directeur de société      5            actif   
..                                                ...    ...              ...   
37                          Employée du secteur privé      1            actif   
38                                   En disponibilité      1            actif   
39                                          Etudiante      1  Sans Profession   
40                                      Fonctionnaire      1            actif   
41                       Fonctionnaire de catégorie A     24            actif   
42                       Fonctionnaire de catégorie B      3            actif   
43           Fonctionnaire de l'État en disponibilité      1            actif   
44           Fonctionnaire des grands corps de l'État      1            actif   
45                             Fonctionnaire retraité      1         retraite   
46                          Fonctionnaire territorial      4            actif   
47           Fonctionnaire territorial de catégorie A      1            actif   
48                         Fonctionnaire territoriale      1            actif   
49                                      Informaticien      1            actif   
50                                          Ingénieur      9            actif   
51                                         Ingénieure      1            actif   
52                             Personnel de direction      1            actif   
53                                Profession libérale      5            actif   
54         Responsable de relations institutionnelles      1            ac